version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: areal-hr-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - areal-network

  server:
    build:
      context: ./server
      dockerfile: ./containers/server/Dockerfile
    container_name: areal-hr-server
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - APP_URL=${APP_URL}
      - APP_PORT=${APP_PORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - areal-network
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: ./containers/client/Dockerfile
    container_name: areal-hr-client
    ports:
      - "${VITE_APP_PORT}:3000"
    depends_on:
      - server
    environment:
      - VITE_APP_URL=${VITE_APP_URL}
      - VITE_APP_PORT=${VITE_APP_PORT}
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - areal-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: areal-hr-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - areal-network

networks:
  areal-network:
    driver: bridge

volumes:
  postgres_data: